using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace BurgerShop.UI
{
    // Display-only catalog. Never apply to object names, save keys or gameplay identifiers.
    public static class GameChinese
    {
        static readonly Dictionary<string,string> Copy = new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
        {

            { "Own space: machine", "自有空间：机器" },
            { "Optional wing", "可选侧翼" },
            { "· total", "· 合计" },
            { "Production is short of demand", "持续缺货：先改善生产" },
            { "Stock is waiting for transport", "机上有货：先改善搬运" },
            { "Stock ready · customers are waiting", "柜台有货：改善出餐速度" },
            { "Clean seats are full", "干净座位已满：增加座位" },
            { "Service interval", "出餐间隔" },
            { "Hire staff first", "先雇用员工" },
            { "No valid star source · progression needs review", "暂无可用投资" },
            { "No eligible upgrade found; check land and staff access. This is not a sell-more task.", "请检查扩建与员工是否已开放" },
            { "Tap the character or this card to upgrade", "点击人物或本卡片升级" },
            { "Tap to locate · other investments also earn stars", "点击定位，也可选择其他投资" },
            { "Expand main hall & hire staff", "扩建主厅并雇用员工" },
            { "Upgrade burger machine", "升级汉堡机" },
            { "Upgrade cola machine", "升级可乐机" },
            { "Upgrade player speed", "提升移动速度" },
            { "Upgrade player carry", "提升携带能力" },
            { "Upgrade staff speed", "提升员工速度" },
            { "Upgrade staff carry", "提升员工携带" },
            { "Upgrade table ·", "更换餐桌 ·" },
            { "Expand main hall", "扩建主厅" },
            { "More workspace · staff access · land", "增加空间，开放员工 · 土地" },
            { "+ first staff", "+ 首位员工" },
            { "Hire your first employee ·", "雇用首位员工 ·" },
            { "then hire staff", "再雇用员工" },
            { "Second burger machine ·", "第二台汉堡机 ·" },
            { "Blue-box packing ·", "蓝盒打包台 ·" },
            { "Car orders need blue boxes · build packing", "汽车订单需要蓝盒，请先建打包台" },
            { "Cola opening: land", "可乐区：土地" },
            { "+ machine", "+ 机器" },
            { "+ counter", "+ 柜台" },
            { "Clear a used dining table", "清理一张餐桌" },
            { "Let staff complete an order", "让员工完成一单" },
            { "Produce on the second grill", "用第二台机器生产汉堡" },
            { "Pack a blue box", "打包一个蓝盒" },
            { "Complete a drive-thru order", "完成一单汽车订单" },
            { "Sell a cup of cola", "卖出一杯可乐" },
            { "Complete a courier order", "完成一单骑手订单" },
            { "Fulfil an automated courier order", "完成一单自动配送" },
            { "Grow cash income", "提升营业收入" },
            { "Choose an investment", "选择一项经营投资" },
            { "Table & chairs", "餐桌椅" },
            { "Dining counter", "堂食柜台" },
            { "Boxing table", "打包台" },
            { "Bistro", "小馆款" },
            { "Diner", "快餐款" },
            { "Patio", "庭院款" },
            { "Item every", "出餐间隔" },
            { "Packing", "打包" },
            { "Style", "款式" },
            { "Tip", "小费" },
            { "Production", "生产" },
            { "Speed", "速度" },
            { "Carry", "携带" },
            { "Meal pay", "餐费" },
            { "eat", "用餐" },
            { "+3% empty speed", "空手速度 +3%" },
            { "stars to upgrade", "星可升级" },
            { "stars", "星" },
            { "coins", "金币" },
            { "Earn", "还差" },
            { "SUPERMARKET", "设施商城" },
            { "Dining, cleaning & trash bins", "堂食、清桌和垃圾桶" },
            { "Second grill, burger counter & restroom", "第二台汉堡机、柜台和卫生间" },
            { "Cola lounge, four-seat & square tables", "可乐区、四人桌和方桌" },
            { "Courier tray & red-box packing", "骑手取餐与红盒打包" },
            { "Conveyor automation", "传送带自动生产" },
            { "West bag machines & pickup", "外卖打包与取餐" },
            { "cash income & shop sign", "营业收入与店铺招牌" },
            { "Dining tables", "堂食餐桌" },
            { "Dining", "堂食" },
            { "Hire staff", "雇用员工" },
            { "Second grill", "第二台汉堡机" },
            { "Blue-box packing", "蓝盒打包台" },
            { "DRIVE-THRU", "汽车取餐" },
            { "Cola wing", "可乐区" },
            { "Courier", "骑手配送" },
            { "Automation", "自动生产" },
            { "Staff speed", "员工速度" },
            { "Staff carry", "员工携带" },
            { "Player speed", "玩家速度" },
            { "Player carry", "玩家携带" },
            { "Pair table", "双人桌" },
            { "Four-seat table", "四人餐桌" },
            { "Square table", "方形餐桌" },
            { "Classic", "经典款" },
            { "Modern", "现代款" },
            { "Premium", "高收益款" },
            { "Rustic", "田园款" },
            { "West wing", "外卖区" },
            { "Cash income", "营业收入" },
            { "Upgrade", "升级" },
            { "Your team kept the shop open", "员工一直在帮你营业" },
            { "Up to 8 hours of after-hours earnings.", "离线收益最多累计 8 小时。" },
            { "Hire an employee to earn while away.", "雇用员工后，离线也能获得收益。" },
            { "While you were away for", "你离开了" },
            { "You were away for", "你离开了" },
            { "employees minded the shop.", "名员工继续营业。" },
            { "cash added", "金币已到账" },
            { "your", "你的" },
            { "hours", "小时" },
            { "minutes", "分钟" },
            { "Sound\nOn", "音效\n开启" },
            { "Sound\nOff", "音效\n关闭" },
            { "My facilities", "我的设施" },
            { "Drinks lounge", "可乐休息区" },
            { "Takeaway workshop", "外卖工作间" },
            { "Main hall", "主厅" },
            { "Select in restaurant", "在店内选择" },
            { "Swipe to browse", "滑动查看更多" },
            { "Rotate left", "向左旋转" },
            { "Rotate right", "向右旋转" },
            { "Tap a facility to move it · Done to finish", "点击设施进行移动，完成后点“完成”" },
            { "Plan your next space · equipment sold separately", "规划扩建空间，设备需另购" },
            { "Choose a model · Pay after placement", "选择设施，摆放完成后付款" },
            { "Choose a facility · Details / Move", "选择设施，查看详情或移动" },
            { "Cola lounge and seating", "可乐休息区与座位" },
            { "Guest facilities · two cubicles", "顾客卫生间 · 两个隔间" },
            { "Toilets and washbasin included", "包含马桶与洗手台" },
            { "Complete room", "整间价格" },
            { "Paper bags → packing → pickup", "纸袋制作 → 打包 → 取餐" },
            { "More working space · Staff access · +2 stars", "增加空间，开放员工 · +2 星" },
            { "First staff opening · Still needed", "扩建并雇用首位员工，还需" },
            { "First expand main hall", "请先扩建主厅" },
            { "Placed. Select another facility, or Done.", "已摆放，可继续选择设施或点“完成”。" },
            { "Checking space and paths...", "正在检查空间与通道…" },
            { "Aligned · drag away to release · Done to place", "已对齐，拖远可解除；点“完成”摆放" },
            { "Drag to position · rotate · tap Done to place", "拖动和旋转调整位置，点“完成”摆放" },
            { "Done to save", "点“完成”保存" },
            { "Not unlocked", "尚未解锁" },
            { "Invalid position", "此处无法摆放" },
            { "Keep the whole facility inside owned land", "请将整个设施放在已购区域内" },
            { "Overlaps another facility", "与其他设施重叠" },
            { "Keep the vehicle lane clear", "请保持车道畅通" },
            { "Overlaps a fixed wall", "与墙体重叠" },
            { "Keep the conveyor clear", "请勿遮挡传送带" },
            { "The entire vehicle lane needs free owned space", "整条车道都需要空闲的已购空间" },
            { "Keep the restroom entrance clear", "请保持卫生间入口畅通" },
            { "Keep work and seat positions inside the shop", "工作位和座位需位于店内" },
            { "A work or seat position is blocked", "工作位或座位被挡住了" },
            { "Wait for the customer to pass", "请等顾客走过后再摆放" },
            { "Wait for the employee to pass", "请等员工走过后再摆放" },
            { "Move away from the placement first", "请先离开要摆放的位置" },
            { "No clear conveyor connection, or loaded chain is too short", "传送带无法连接，或载货段太短" },
            { "Blocks an existing work position", "挡住了现有工作位" },
            { "Keep room entrances reachable", "请保持各房间入口可达" },
            { "Blocks access to", "挡住了通往此处的路：" },
            { ". Drag to leave a wider path.", "，请拖动设施留出通道。" },
            { "Leave a walkable route to the facility", "请为设施留出可通行的路线" },
            { "Price updated:", "价格已更新：" },
            { "coins · tap Done to confirm", "金币，点“完成”确认" },
            { "Not enough coins", "金币不足" },
            { "Not enough cash", "金币不足" },
            { "already paid · only the remaining amount is charged", "已付，仅需支付剩余金额" },
            { "already paid · each tier charges only the remaining amount", "已付，选择款式后仅支付差额" },
            { "All available upgrades installed", "已升至满级" },
            { "Ready for service", "可以开始营业" },
            { "Choose Move to rearrange", "点击“移动”调整位置" },
            { "No further upgrades for this facility", "此设施已无可用升级" },
            { "Choose · Paid", "选择 · 已付款" },
            { "Upgrade unavailable — check cash and level", "暂时无法升级，请检查金币和等级" },
            { "New table set installed!", "餐桌已换新！" },
            { "Unable to buy this set — check remaining cash", "购买失败，请检查所需金币" },
            { "Upgraded!", "升级成功！" },
            { "Level Up!", "升级成功！" },
            { "Shop upgrade ready!", "店铺可以升级了！" },
            { "Shop upgrades", "店铺升级" },
            { "Player upgrades", "玩家升级" },
            { "Staff upgrades", "员工升级" },
            { "Upgrade your character", "提升移动与搬运能力" },
            { "Upgrades apply to all hired staff", "升级对所有已雇员工生效" },
            { "Expand main hall first", "请先扩建主厅" },
            { "Speed (u/s)", "移动速度（单位/秒）" },
            { "+3% speed", "速度 +3%" },
            { "Dining table", "双人餐桌" },
            { "Burger machine", "汉堡机" },
            { "Cola machine", "可乐机" },
            { "Red-box packing", "红盒打包台" },
            { "Paper bag machine", "纸袋机" },
            { "Bag machine", "纸袋机" },
            { "Bagging table", "纸袋打包台" },
            { "Burger counter", "汉堡柜台" },
            { "Cola counter", "可乐柜台" },
            { "Drive-thru counter", "汽车取餐窗口" },
            { "Pickup counter", "外卖取餐柜台" },
            { "Courier pickup tray", "骑手取餐台" },
            { "Trash bin", "垃圾桶" },
            { "Bag production", "纸袋制作时间" },
            { "Facility level", "设施等级" },
            { "Remaining to open", "开业还需" },
            { "land included", "已含土地" },
            { "Packing still needed", "打包设备还需" },
            { "First car window included at", "首个汽车窗口免费开放于" },
            { "Machine", "机器" },
            { "Counter", "柜台" },
            { "Pickup", "取餐" },
            { "NEW GAME - AUTOSAVE ON", "新游戏已创建，自动保存已开启" },
            { "NEWER SAVE - SAVING DISABLED", "存档版本较新，已停止覆盖保存" },
            { "SAVE UNREADABLE - FILES KEPT", "存档无法读取，原文件已保留" },
            { "SAVE UNAVAILABLE", "暂时无法读取存档" },
            { "PROGRESS RESTORED", "进度已恢复" },
            { "BACKUP RESTORED", "已从备份恢复进度" },
            { "SAVE FAILED - RETRYING", "保存失败，正在重试" },
            { "PROGRESS SAVED", "进度已保存" },
            { "SAVE FAILED - OFFLINE PAYMENT NOT APPLIED", "保存失败，离线收益暂未入账" },
            { "This shop will be removed.", "删除后，此店铺进度将被清除。" },
            { "Save now", "立即保存" },
            { "New game", "新建游戏" },
            { "Saves", "存档管理" },
            { "Delete", "删除" },
            { "Cancel", "取消" },
            { "Load", "读取" },
            { "Now", "当前" },
            { "Shop", "店铺" },
            { "Continue", "继续" },
            { "Close", "关闭" },
            { "Done", "完成" },
            { "Details", "详情" },
            { "Buy", "购买" },
            { "Build", "建造" },
            { "Built!", "已建成！" },
            { "Built", "已建成" },
            { "Locked", "未解锁" },
            { "Included", "已包含" },
            { "Restroom", "卫生间" },
            { "Upgraded", "已升级" },
            { "Move", "移动" },
            { "SELECT", "选择" },
            { "TABLE CHANGE", "更换餐桌" },
            { "Value", "实惠款" },
            { "Turnover", "高效款" },
            { "Starter", "基础款" },
            { "SAME SPEED", "用餐速度不变" },
            { "SPEED +20%", "用餐速度 +20%" },
            { "SLOWER", "用餐稍慢" },
            { "PAY", "餐费" },
            { "meal", "每餐" },
            { "Bag every", "纸袋间隔" },
            { "BAG TABLE", "纸袋打包台" },
            { "Need burgers", "需要汉堡" },
            { "Need bags", "需要纸袋" },
            { "WEST EXPANSION", "外卖区扩建" },
            { "Tap star → Expand", "点击星条 → 扩建" },
            { "FULL", "已满" },
            { "MAX LEVEL", "已满级" },
            { "MAX", "满级" },
            { "PICK SET", "选择款式" },
            { "STAFF FULL", "员工已满" },
            { "Staff available", "可雇用员工" },
            { "No further hires", "无需再雇用" },
            { "Go to the HR office", "前往人事室" },
            { "Stocks counter, serves, clears tables", "补货、收银和清桌" },
            { "Stock, serve, and clear tables", "补货、收银和清桌" },
            { "Hiring unavailable", "暂时无法雇用" },
            { "Stay here to hire", "站在此处雇用" },
            { "hired · next", "已雇用 · 下次需" },
            { "Ready to work", "准备工作" },
            { "Walking to cola", "前往可乐机" },
            { "Walking to grill", "前往汉堡机" },
            { "Waiting for cola", "等待可乐" },
            { "Waiting for burgers", "等待汉堡" },
            { "Walking to serve", "前往收银" },
            { "Carrying to counter", "正在向柜台搬运" },
            { "Walking to a dirty table", "前往待清理餐桌" },
            { "Clearing a table", "正在清桌" },
            { "Taking trash to the bin", "正在运送垃圾" },
            { "Dumping trash", "正在倒垃圾" },
            { "Boxing a burger", "正在打包汉堡" },
            { "Stocking the package counter", "正在补充打包柜台" },
            { "Selling a combo", "正在出售套餐" },
            { "Serving a cola customer", "正在出售可乐" },
            { "Serving a customer", "正在服务顾客" },
            { "Stocking the counter", "正在补充柜台" },
            { "Waiting to serve", "等待顾客" },
            { "Install a wing", "建造可乐侧翼" },
            { "Install a cola bar", "建造可乐柜台" },
            { "Install a cola", "建造可乐机" },
            { "Install a table", "摆放餐桌" },
            { "a 4-seat table", "四人桌" },
            { "a square table", "方桌" },
            { "a boxing table", "打包台" },
            { "a drive-thru", "汽车取餐窗口" },
            { "a counter", "柜台" },
            { "a grill", "汉堡机" },
            { "a wing", "可乐侧翼" },
            { "a cola bar", "可乐柜台" },
            { "a cola", "可乐机" },
            { "a table", "餐桌" },
            { "Install", "建造" },
            { "Enter", "进入" },
            { "Remind", "提醒" },
            { "Calling", "通话中" },
            { "Clear", "清理" },
            { "BUSY", "使用中" },
            { "FREE", "空闲" },
            { "CLEAN", "清洁" },
            { "WC", "卫生间" },
            { "HR", "人事室" },
            { "STOP", "停车" },
            { "EXPRESS", "骑手取餐" },
            { "DRINKS & SEATING", "饮品休息区" },
            { "DRINKS", "饮品区" },
            { "TAKEAWAY", "外卖区" },
            { "DELIVERY", "配送区" },
            { "GRILL", "汉堡机" },
            { "COLA", "可乐" },
            { "BURGER", "汉堡" },
            { "BAGS", "纸袋" },
            { "PACKED", "已打包" },
            { "RAW", "待打包" },
            { "BOX", "盒装" },
            { "PACK", "打包" },
            { "OUT", "成品" },
            { "WINDOW", "取餐窗口" },
            { "WING", "侧翼" },
            { "BAR", "饮品柜台" },
            { "FOUR", "四人桌" },
            { "4-SEAT", "四人桌" },
            { "SQUARE", "方桌" },
            { "TABLE", "餐桌" },
            { "LANE", "车道" },
            { "TRASH", "垃圾" },
            { "DELIVERED", "已送达" },
            { "STAFF", "员工" },
            { "Stock", "库存" },
            { "Paid", "已付" },
            { "Due", "应付" },
            { "Base", "基础价" },
            { "Current", "当前" },
            { "Land", "土地" },
            { "Balance", "余额" },
            { "Remaining", "剩余" },
            { "Price", "价格" },
            { "Unlocks at", "解锁等级：" },
            { "unlock", "解锁" },
            { "Need", "还差" },
            { "more coins", "金币" },
            { "more stars", "星" },
            { "more", " " },
            { "coin", "金币" },
            { "cash", "金币" },
            { "star", "星" },
            { "Level", "等级" },
            { "Ready", "已就绪" },
            { "Cost", "费用" },
            { "Completed", "已完成" },
            { "Complete", "完成" },
            { "Still needed", "还需" },
            { "Next", "下一次" },
            { "Waiting", "等待中" },
            { "Collect", "拾取" },
            { "Serve", "收银" },
            { "Unload to collect", "先放下物品再拾取" },
            { "Next order: 1 BURGER", "下一单：1 个汉堡" },
            { "Customers are arriving", "顾客正在进店" },
            { "Walking to the queue", "正在前往队尾" },
            { "CUSTOMERS", "顾客" },
            { "First order complete · Upgrade to unlock dining", "首单完成，升级即可开放堂食" },
            { "Sell your first burger · Pick up a burger", "卖出首个汉堡 · 先取一个汉堡" },
            { "Put the burger on the counter", "把汉堡放上柜台" },
            { "Stand at the register · Serve your first order", "站到收银处，完成首单" },
            { "Sell your first burger", "卖出首个汉堡" },
            { "Pick up a burger", "取一个汉堡" },
            { "Unlock dining", "开放堂食" },
            { "Serve a waiting customer", "服务一位等候顾客" },
            { "Automate supply, serving and cleaning", "自动补货、收银和清桌" },
            { "Add dining seats", "增加堂食座位" },
            { "Add a production station", "增加生产设备" },
            { "Fully upgraded", "已升至满级" },
            { "Upgrade unavailable", "暂时无法升级" },
            { "Stay here to upgrade", "站在此处升级" },
            { "leave and return", "离开后再回来" },
            { "per", "每个" },
            { "Tap", "点击" },
            { "First staff", "首位员工" },
            { "Expansions", "空间扩建" },
            { "Take trash", "收走垃圾" },
            { "Upgrade the grill", "升级汉堡机" },
            { "Boost", "属性强化" },
            { "Install a", "建造" },
            { "Move mouse · Q/E rotate · click to place · Done to finish", "移动鼠标定位，旋转后点击摆放，完成退出" },
            { "X", "×" },
            { "v", "↓" },
        };
        static readonly Regex Phrases = new Regex(string.Join("|", Copy.Keys.OrderByDescending(k=>k.Length)
            .Select(k=>(char.IsLetter(k[0]) ? @"(?<![A-Za-z])" : "") + Regex.Escape(k) +
                (char.IsLetter(k[k.Length-1]) ? @"(?![A-Za-z])" : ""))), RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
        static readonly Regex Level = new Regex(@"\b(?:Lv\.?|LV)\s*(\d+)");
        static readonly Regex Seconds = new Regex(@"(?<=\d)s\b");
        static readonly Regex Times = new Regex(@"\bx(?=\d)");
        public static string Translate(string source)
        {
            if (string.IsNullOrEmpty(source)) return "";
            source=source.Replace("⭐", "★");
            bool latin=false;foreach(char c in source)if((c>='A'&&c<='Z')||(c>='a'&&c<='z')){latin=true;break;}
            if(!latin)return source;
            string copy=Level.Replace(source,"$1级");
            copy=Seconds.Replace(copy,"秒");copy=Times.Replace(copy,"×");
            return Phrases.Replace(copy,m=>Copy[m.Value]);
        }
    }
}
